// Proves the built package actually works, before anything downstream trusts it.
//
// This exists because a build once "passed" while producing a wasm binary that
// could not instantiate at all: an old wasm-opt mangled the externref table, and
// the failure only surfaced two jobs later as
// `WebAssembly.Table.grow(): failed to grow table by 4` — an error that points
// nowhere near the actual cause. A build that emits a broken artifact should
// fail at the build, not downstream.
//
// Deliberately dependency-free: it uses only the crafted fixtures, which are
// generated by a zip writer in this repo, so it can run before `bun install`.
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { crafted } from "../test/support/paths.ts";

const bytes = readFileSync(join(crafted, "errors.xlsx"));
const checks = [];

// Importing the entry runs initSync — this alone catches a module that cannot
// instantiate, which was the original failure. Wrapped so that failure arrives
// as a pointed diagnosis rather than a raw `Table.grow()` stack trace, because
// nothing in that stack suggests looking at the version of your wasm-opt.
let api;
try {
  api = await import("../dist/node.js");
} catch (error) {
  console.error(`✗ the built wasm could not even be instantiated\n\n  ${error.message}\n`);
  if (String(error.message).includes("Table.grow")) {
    console.error(
      "  This is what an out-of-date wasm-opt does to the externref table.\n" +
        "  Check `wasm-opt --version` — binaryen 108, which Ubuntu still ships,\n" +
        "  produces exactly this. The build is pinned to 131.\n",
    );
  }
  process.exit(1);
}
const { readCells, sheetNames, toCsv, toMarkdown } = api;

const names = sheetNames(bytes);
checks.push(["sheetNames", JSON.stringify(names), names.length === 1 && names[0] === "Sheet1"]);

const csv = toCsv(bytes).split("\n")[0];
checks.push(["toCsv", csv, csv === "#DIV/0!"]);

const md = toMarkdown(bytes).split("\n")[1];
checks.push(["toMarkdown", md, md === "| --- |"]);

// Exercises the tagged path too, so a binary that reads numbers but mangles
// anything richer does not slip through.
const first = JSON.parse(readCells(bytes, { tagged: true }))[0][0];
checks.push([
  "readCells tagged",
  JSON.stringify(first),
  first?.t === "err" && first?.v === "#DIV/0!",
]);

let failed = 0;
for (const [name, got, ok] of checks) {
  if (!ok) failed++;
  console.log(`${ok ? "✓" : "✗"} ${name.padEnd(18)} ${got}`);
}

if (failed) {
  console.error(`\nsmoke check failed: the built wasm is not usable\n`);
  process.exit(1);
}
console.log("\nbuilt package is usable\n");
